// Burger Ingredients
export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_ERROR = "GET_INGREDIENTS_ERROR";

// Burger Constructor
export const ADD_BURGER_INGREDIENT = "ADD_BURGER_INGREDIENT";
export const REMOVE_BURGER_INGREDIENT = "REMOVE_BURGER_INGREDIENT";
export const MOVE_BURGER_INGREDIENTS = "SWAP_BURGER_INGREDIENTS"
export const CLEAR_BURGER_INGREDIENTS = "CLEAR_BURGER_INGREDIENTS"

// Ingredient Details
export const SHOW_INGREDIENT_DETAILS = "SHOW_INGREDIENT_DETAILS";
export const HIDE_INGREDIENT_DETAILS = "HIDE_INGREDIENT_DETAILS";

// Order Details
export const CLEAR_ORDER_ID = "CLEAR_ORDER_ID";

// Place Order
export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUSSESS = "PLACE_ORDER_SUSSESS";
export const PLACE_ORDER_ERROR = "PLACE_ORDER_ERROR";
