// Burger Ingredients
export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST"
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS"
export const GET_INGREDIENTS_ERROR = "GET_INGREDIENTS_ERROR"

// Burger Constructor
export const ADD_BURGER_INGREDIENT = "ADD_BURGER_INGREDIENT"
export const REMOVE_BURGER_INGREDIENT = "REMOVE_BURGER_INGREDIENT"

// Ingredient Details
export const SHOW_INGREDIENT_DETAILS = "SHOW_INGREDIENT_DETAILS"
export const HIDE_INGREDIENT_DETAILS = "HIDE_INGREDIENT_DETAILS"